### ISSUE TITLE
Hi, why I can't download your project?

### ISSUE THREAD

**Issue by jenny1022** [lykaust15/Disease_gene_prioritization_GCN#1]
It always shows download failures.

**Comment by lykaust15** [comment]
Hi, for the dataset, you can download through google drive using the link provided. For the code, you can download using the github command
```
git clone https://github.com/lykaust15/Disease_gene_prioritization_GCN.git
```

**Comment by jenny1022** [comment]
hi，after downloading for a while, there will still be an error. Can you send me the file?
------------------ 原始邮件 ------------------
发件人: "Yu Li"<notifications@github.com>;
发送时间: 2019年2月11日(星期一) 晚上8:36
收件人: "lykaust15/Disease_gene_prioritization_GCN"<Disease_gene_prioritization_GCN@noreply.github.com>;
抄送: "李靖怡"<ljy_1121@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lykaust15/Disease_gene_prioritization_GCN] Hi, why I can'tdownload your project? (#1)




Hi, for the dataset, you can download through google drive using the link provided. For the code, you can download using the github command
 git clone https://github.com/lykaust15/Disease_gene_prioritization_GCN.git

**Comment by lykaust15** [comment]
Hi, may I know what error you get?

**Comment by jenny1022** [comment]
of course, I just send you a error picture, it seems you can't see it. 


                      $ git clone https://github.com/lykaust15/Disease_gene_prioritization_GCN.git     Cloning into 'Disease_gene_prioritization_GCN'...                                remote: Enumerating objects: 23, done.                                           remote: Counting objects: 100% (23/23), done.                                    remote: Compressing objects: 100% (17/17), done.                                 error: RPC failed; curl 18 transfer closed with outstanding read data remaining  fatal: the remote end hung up unexpectedly                                       fatal: early EOF                                                                 fatal: index-pack failed                                                           
   



so can you see this?


------------------ 原始邮件 ------------------
发件人: "Yu Li"<notifications@github.com>;
发送时间: 2019年2月11日(星期一) 晚上9:41
收件人: "lykaust15/Disease_gene_prioritization_GCN"<Disease_gene_prioritization_GCN@noreply.github.com>;
抄送: "李靖怡"<ljy_1121@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lykaust15/Disease_gene_prioritization_GCN] Hi, why I can'tdownload your project? (#1)




Hi, may I know what error you get?

**Comment by lykaust15** [comment]
Wired. Here is what I get:
```
git clone https://github.com/lykaust15/Disease_gene_prioritization_GCN.git
Cloning into 'Disease_gene_prioritization_GCN'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 181 (delta 8), reused 16 (delta 6), pack-reused 158
Receiving objects: 100% (181/181), 37.18 MiB | 7.67 MiB/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
```

**Comment by lykaust15** [comment]
I guess you internet connection is slow or somehow the github service is not availabe in your region.
Please find below for the solution:
https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

If it still does not work, I can send you the file by email.

**Comment by jenny1022** [comment]
thank you! I just have tried the solution, but it doesn't work. I guess it is the second reason because I can download other files quickly.  




------------------ 原始邮件 ------------------
发件人: "Yu Li"<notifications@github.com>;
发送时间: 2019年2月11日(星期一) 晚上9:49
收件人: "lykaust15/Disease_gene_prioritization_GCN"<Disease_gene_prioritization_GCN@noreply.github.com>;
抄送: "李靖怡"<ljy_1121@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lykaust15/Disease_gene_prioritization_GCN] Hi, why I can'tdownload your project? (#1)




I guess you internet connection is slow or somehow the github service is not availabe in your region.
 Please find below for the solution:
 https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining
 
If it still does not work, I can send you the file by email.

**Comment by lykaust15** [comment]
I see. What's your email?

**Comment by jenny1022** [comment]
My email is  ljy_1121@qq.com.


Also can I ask a question of your paper? I really would like to know what the final input (learning embedding) vector is about node embedding with graph convolution. With the learning embedding of the disease node d you mentioned in edge prediction, is it a feature matrix?






------------------ 原始邮件 ------------------
发件人: "Yu Li"<notifications@github.com>;
发送时间: 2019年2月11日(星期一) 晚上10:16
收件人: "lykaust15/Disease_gene_prioritization_GCN"<Disease_gene_prioritization_GCN@noreply.github.com>;
抄送: "李靖怡"<ljy_1121@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lykaust15/Disease_gene_prioritization_GCN] Hi, why I can'tdownload your project? (#1)




I see. What's your email?

**Comment by lykaust15** [comment]
Got it. You are in the mainland, China, which should explain the network problem you got. 

I will explain it in the email.

**Comment by jenny1022** [comment]
Dear yu:


Thank you for your reply, I am sorry for I just made a mistake, in fact I want to know the output of first step(Node embedding with graph convolution). I'm so sorry to bother you. 





------------------ 原始邮件 ------------------
发件人: "Yu Li"<notifications@github.com>;
发送时间: 2019年2月11日(星期一) 晚上10:26
收件人: "lykaust15/Disease_gene_prioritization_GCN"<Disease_gene_prioritization_GCN@noreply.github.com>;
抄送: "李靖怡"<ljy_1121@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lykaust15/Disease_gene_prioritization_GCN] Hi, why I can'tdownload your project? (#1)




Got it. You are in the mainland, China, which should explain the network problem you got.
 
I will explain it in the email.

**Comment by lykaust15** [comment]
No problem. 
Yes, the output can be considered as the feature matrix. GCN is basically a functional mapping, which can map the irregular data structure into a unified space. Here is a figure from a review paper I am currently working on. The reivew paper will introduce the idea of GCN in a more easy to understand way. The manuscript would be make online soon.

<img width="473" alt="screen shot 2019-02-11 at 17 48 01" src="https://user-images.githubusercontent.com/19503832/52570808-57031c00-2e25-11e9-837e-ca54bc11bb11.png">

**Comment by jenny1022** [comment]
Thanks a lot! It is really nice. Hope you everything goes well and look forward to seeing your new work.




------------------ 原始邮件 ------------------
发件人: "Yu Li"<notifications@github.com>;
发送时间: 2019年2月11日(星期一) 晚上10:50
收件人: "lykaust15/Disease_gene_prioritization_GCN"<Disease_gene_prioritization_GCN@noreply.github.com>;
抄送: "李靖怡"<ljy_1121@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lykaust15/Disease_gene_prioritization_GCN] Hi, why I can'tdownload your project? (#1)




No problem.
 Yes, the output can be considered as the feature matrix. GCN is basically a functional mapping, which can map the irregular data structure into a unified space. Here is a figure from a review paper I am currently working on. The reivew paper will introduce the idea of GCN in a more easy to understand way. The manuscript would be make online soon.
